# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Zhen Li
description: >- # this means to ignore newlines until "baseurl:"
  Personal page of Zhen Li.
baseurl: "" # the subpath of the site
url: "https://paper99.github.io" # the base hostname & protocol for the site
og_image: /assets/img/zhenli.jpeg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publication
    - name: Misc

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: yourmail@domain.com
      link: mailto:yourmail@domain.com
    - name: WeChat
      value: YourWeChatUsername
      link: "#"
  follow:
    - name: Google scholar
      link: https://scholar.google.com/citations?user=utI5YFEAAAAJ&hl=en
    - name: GitHub
      link: http://github.com/Paper99

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
